import type { Creator } from "@vuqiro/types";

export const mockCreators: Creator[] = [
  {
    id: "creator_001",
    userId: "user_001",
    handle: "maya",
    displayName: "Maya North",
    bio: "Daily edits, music moments and creator drops.",
    bannerTone: "violet",
    category: "Music",
    followerCount: 128400,
    subscriberCount: 4200,
    totalLikes: 890000,
    totalVideos: 84,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 8420,
    subscriptionRevenue: 15900,
    tiersEnabled: ["support", "plus", "premium"],
    createdAt: "2025-09-14T09:00:00Z"
  },
  {
    id: "creator_002",
    userId: "user_002",
    handle: "riven",
    displayName: "Riven Atlas",
    bio: "Travel cuts, city nights and behind-the-scenes stories.",
    bannerTone: "cyan",
    category: "Travel",
    followerCount: 84200,
    subscriberCount: 1800,
    totalLikes: 420000,
    totalVideos: 52,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 1,
    coinRevenue: 3980,
    subscriptionRevenue: 6800,
    tiersEnabled: ["support", "plus"],
    createdAt: "2025-10-02T18:30:00Z"
  },
  {
    id: "creator_003",
    userId: "user_003",
    handle: "noorbuilds",
    displayName: "Noor Builds",
    bio: "Creator tools, app building and product breakdowns.",
    bannerTone: "emerald",
    category: "Tech",
    followerCount: 36100,
    subscriberCount: 920,
    totalLikes: 156000,
    totalVideos: 38,
    isVerified: false,
    verificationStatus: "pending",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 1240,
    subscriptionRevenue: 2900,
    tiersEnabled: ["support"],
    createdAt: "2025-11-20T12:00:00Z"
  },
  {
    id: "creator_004",
    userId: "user_004",
    handle: "solacooks",
    displayName: "Sola Cooks",
    bio: "Fast recipes, street food hunts and kitchen experiments.",
    bannerTone: "amber",
    category: "Food",
    followerCount: 214800,
    subscriberCount: 6900,
    totalLikes: 1420000,
    totalVideos: 121,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 15200,
    subscriptionRevenue: 26100,
    tiersEnabled: ["support", "plus", "premium"],
    createdAt: "2025-08-01T08:00:00Z"
  },
  {
    id: "creator_005",
    userId: "user_005",
    handle: "kaimoves",
    displayName: "Kai Moves",
    bio: "Movement, calisthenics and training with zero equipment.",
    bannerTone: "rose",
    category: "Fitness",
    followerCount: 97300,
    subscriberCount: 3100,
    totalLikes: 610000,
    totalVideos: 76,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 5300,
    subscriptionRevenue: 11400,
    tiersEnabled: ["support", "plus"],
    createdAt: "2025-09-28T14:00:00Z"
  },
  {
    id: "creator_006",
    userId: "user_006",
    handle: "lumen.art",
    displayName: "Lumen Art",
    bio: "Digital painting timelapses and process breakdowns.",
    bannerTone: "violet",
    category: "Art",
    followerCount: 45900,
    subscriberCount: 1350,
    totalLikes: 232000,
    totalVideos: 44,
    isVerified: false,
    verificationStatus: "unverified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 2100,
    subscriptionRevenue: 4300,
    tiersEnabled: ["support", "plus"],
    createdAt: "2025-12-05T10:00:00Z"
  },
  {
    id: "creator_007",
    userId: "user_007",
    handle: "vera.codes",
    displayName: "Vera Codes",
    bio: "One-minute coding lessons and dev career advice.",
    bannerTone: "cyan",
    category: "Tech",
    followerCount: 68200,
    subscriberCount: 2400,
    totalLikes: 355000,
    totalVideos: 61,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 0,
    coinRevenue: 4100,
    subscriptionRevenue: 8800,
    tiersEnabled: ["support", "plus", "premium"],
    createdAt: "2025-10-19T16:00:00Z"
  },
  {
    id: "creator_008",
    userId: "user_008",
    handle: "dunestyle",
    displayName: "Dune Style",
    bio: "Streetwear fits, thrift flips and style on a budget.",
    bannerTone: "amber",
    category: "Fashion",
    followerCount: 156700,
    subscriberCount: 5200,
    totalLikes: 980000,
    totalVideos: 98,
    isVerified: true,
    verificationStatus: "verified",
    onboardingStatus: "completed",
    monetizationEnabled: true,
    moderationWarnings: 2,
    coinRevenue: 9800,
    subscriptionRevenue: 19400,
    tiersEnabled: ["support", "plus"],
    createdAt: "2025-08-22T11:00:00Z"
  },
  {
    id: "creator_009",
    userId: "user_009",
    handle: "orbitplays",
    displayName: "Orbit Plays",
    bio: "Indie game discoveries and speedrun highlights.",
    bannerTone: "emerald",
    category: "Gaming",
    followerCount: 52400,
    subscriberCount: 1600,
    totalLikes: 288000,
    totalVideos: 57,
    isVerified: false,
    verificationStatus: "pending",
    onboardingStatus: "completed",
    monetizationEnabled: false,
    moderationWarnings: 0,
    coinRevenue: 0,
    subscriptionRevenue: 0,
    tiersEnabled: ["support"],
    createdAt: "2026-01-10T20:00:00Z"
  },
  {
    id: "creator_010",
    userId: "user_010",
    handle: "aria.sound",
    displayName: "Aria Sound",
    bio: "Original beats, sound design and studio sessions.",
    bannerTone: "rose",
    category: "Music",
    followerCount: 30800,
    subscriberCount: 740,
    totalLikes: 121000,
    totalVideos: 29,
    isVerified: false,
    verificationStatus: "unverified",
    onboardingStatus: "in_progress",
    monetizationEnabled: false,
    moderationWarnings: 0,
    coinRevenue: 0,
    subscriptionRevenue: 0,
    tiersEnabled: [],
    createdAt: "2026-02-14T13:00:00Z"
  }
];
